[package]
name = "test-http-requests"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "request"
path = "request.rs"

[dependencies]
reqwest = { version = "0.12.22", features = ["blocking"] }
tokio = { version = "1.46.1", features = ["full"] }
